apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: node-app
spec:  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-app
  replicas: 3 
  template: 
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 635261526007.dkr.ecr.us-east-1.amazonaws.com/web:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: default
  labels:
    app: node-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-app
  type: LoadBalancer
